### ISSUE TITLE
Unable to install since update

### ISSUE THREAD

**Issue by jamierocks** [thoughtbot/neat#429]
```bash
jamie@Jamies-Mac-mini  ~/proj/lexteam/site/indigo/src/scss   master ●  neat install
/Library/Ruby/Gems/2.0.0/gems/neat-1.7.3/lib/neat.rb:18:in `<module:Neat>': uninitialized constant Neat::Sass (NameError)
        from /Library/Ruby/Gems/2.0.0/gems/neat-1.7.3/lib/neat.rb:4:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/neat-1.7.3/bin/neat:3:in `<top (required)>'
        from /usr/local/bin/neat:23:in `load'
        from /usr/local/bin/neat:23:in `<main>'
```

**Comment by tysongach** [comment]
@jamierocks Hi! Which update?

**Comment by jamierocks** [comment]
neat-1.7.3

**Comment by jamierocks** [comment]
Perhaps my ruby installation is old, upgrading.

**Comment by tysongach** [comment]
I’m seeing this, as well. I’m on Ruby 2.3.0.

**Comment by jamierocks** [comment]
Yeah even after upgrading I get the same thing.

**Comment by tysongach** [comment]
@jamierocks Do you have the Bourbon 5.0 beta or alpha installed?

**Comment by jamierocks** [comment]
Nope

**Comment by tysongach** [comment]
@jamierocks We think we tracked the problem down and I just cut a release with a fix. Can you install Neat `1.7.4` and see if this issue is resolved?

**Comment by jamierocks** [comment]
Yeah - I'll do that some time tonight

**Comment by wardpenney** [comment]
Thanks for looking into it @tysongach!
